package net.tarilabs.mpes

import com.rapplogic.xbee.api.XBeeAddress64;
import com.rapplogic.xbee.api.zigbee.ZNetRxIoSampleResponse;

import function net.tarilabs.camelxbeeapi.XBeeAPIUtils.addressAsMacFormat;

/** 
 * Filter01
 * Remove everything which is not from the XBee 00:13:A2:00:40:68:E0:00
 *
 */
rule "Filter01"
no-loop
salience -1000
dialect "mvel" 
    when
        $o : ZNetRxIoSampleResponse(
        		eval( ! addressAsMacFormat(remoteAddress64).equals("00:13:A2:00:40:68:E0:00") ) 
        	 )
    then
       	retract($o);
end

/**
 * Filter02
 * Remove non-analog reading packets from XBee 00:13:A2:00:40:68:E0:00
 *
 */
rule "Filter02"
no-loop 
salience -1000
dialect "mvel" 
    when
        $o : ZNetRxIoSampleResponse(
				eval( addressAsMacFormat(remoteAddress64).equals("00:13:A2:00:40:68:E0:00") ) , 
				containsAnalog == false
			 )
    then
       	retract($o);
end